### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by clairekrogers** [emwads/RunThisPlace#1]
* MVP: every feature has the same 3 bullet points.  Customize each feature's notes to explain what that feature is expected to do.  Make it clear what your site does. 
* Phase 1:  separate out front-end auth from `workout` backend setup.  Leave at least a day for front-end auth 
* `Route` might be a reserved word in Rails.  I recommend changing it. 
* Phase 2: says routes can be created/destroyed through API.  What about front-end user interaction?  Does this phase include the map interface?  That will be one of the trickiest parts of this project.  
* Remove styling from phases 4 and 6.  Styling should be done in tandem with component development.  Do not leave styling until the end.

**Comment by emwads** [comment]
- Detailed site features
- Adjusted the timeline to allow for more time for front end auth
- Changed `Route` to RunRoute
- Clarified wording so that user interaction with routes is via a google maps api
- Styling phases have been removed
