### ISSUE TITLE
Flux Cycles

### ISSUE THREAD

**Issue by clairekrogers** [emwads/RunThisPlace#2]
* Do you want people to be able to update routes?  I think this will be extremely tricky, and should probably be a bonus feature. 
* What is the use case for `fetchSingleFriend`? 
* What is `RouteSearchSuggestion Cycles?`

**Comment by emwads** [comment]
- I've removed the editing of routes
- removed fetchSingleFriend actions/utils -- there's no point in having that action
- added more info to RouteSearching -- this allows for text searching of routes in the create workout form -- this might end up being a bonus feature.
